var lesson = {};

lesson[1] = [
  [ '私　（わたし）', 'I' ],
  [ 'わたしたち', 'we' ],
  [ 'あなた', 'you' ],
  [ 'あの人　（あのひと）', 'that person, he, she' ],
  [ 'あの方　（あのかた）', 'that person, he, she (polite)' ],
  [ '皆さん　（みなさん）', 'everybody' ],
  [ '＿さん', 'Mr., Ms. _' ],
  [ '＿ちゃん', 'girl suffix' ],
  [ '＿くん', 'boy suffix' ],
  [ '＿人　（＿じん）', 'people of _' ],
  [ '先生　（せんせい）', 'teacher (with respect)' ],
  [ '教師　（きょうし）', 'teacher (job)' ],
  [ '学生　（がくせい）', 'student' ],
  [ '会社員　（かいしゃいん）', 'company employee' ],
  [ '＿の社員　（＿のしゃいん）', 'employee of _ company' ],
  [ '銀行員　（ぎんこういん）', 'bank employee' ],
  [ '医者　（いしゃ）', '(medical) doctor' ],
  [ '研究者　（けんきゅうしゃ）', 'scholar, researcher' ],
  [ 'エンジニア', 'engineer' ],
  [ 'マーケティングのスタッフ', 'marketing staff' ],
  [ '大学　（だいがく）', 'university' ],
  [ '病院　（びょういん）', 'hospital' ],
  [ '電気　（でんき）', 'light, electricity' ],
  [ 'だれ', 'who' ],
  [ 'どなた', 'who (polite)' ],
  [ 'はい', 'yes' ],
  [ 'いいえ', 'no' ]
];
